version: '3.8'

services:
  users:
    build: ./users
    container_name: users_api
    volumes:
      - ./users:/app
    ports:
      - "7000:7000"
    env_file:
      - ./.env
    depends_on:
      - "mongo_db"
  
  auth:
    build: ./auth
    container_name: auth_api
    volumes:
      - ./auth:/app
    env_file:
      - ./.env
    depends_on:
      - "mongo_db"

  games:
    build: ./games
    container_name: games_api
    volumes:
      - ./games:/app
    ports:
      - "7002:7002"
    env_file:
      - ./.env
    depends_on:
      - "mongo_db"

  mongo_db:
    image: mongo
    container_name: db_mongo
    restart: always
    env_file:
      - ./.env
    volumes:
      - data:/data/db

volumes:
  data:

  
     